INSERT INTO UF(sigla_uf, nome_uf) VALUES('AC','ACRE');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('AL','ALAGOAS');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('AP','AMAPÁ');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('AM','AMAZONAS');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('BA','BAHIA');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('CE','CEARÁ');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('DF','DISTRITO FEDERAL');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('ES','ESPÍRITO SANTO');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('GO','GOIÁS');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('MA','MARANHÃO');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('MT','MATO GROSSO');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('MS','MATO GROSSO DO SUL');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('MG','MINAS GERAIS');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('PA','PARÁ');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('PB','PARAÍBA');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('PR','PARANÁ');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('PE','PERNAMBUCO');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('PI','PIAUÍ');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('RJ','RIO DE JANEIRO');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('RN','RIO GRANDE DO NORTE');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('RS','RIO GRANDE DO SUL');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('RO','RONDÔNIA');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('RR','RORAIMA');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('SC','SANTA CATARINA');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('SP','SÃO PAULO');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('SE','SERGIPE');
INSERT INTO UF(sigla_uf, nome_uf) VALUES('TO','TOCANTINS');
